"""
Audit log for the Input Orchestration Layer — ADR-002.

Every ControlInput processed by the InputOrchestrator produces a
ControlInputAuditRecord. The AuditLog accumulates these records so that
any scenario can be reproduced by replaying its audit log in order.

Milestone 1 AuditLog is in-memory. Persistent storage (PostgreSQL) is
introduced in Milestone 2 alongside the database layer. The interface
is stable — Milestone 2 replaces only the storage backend.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from datetime import datetime

    from app.simulation.orchestration.inputs import InputSource


# ---------------------------------------------------------------------------
# Audit record
# ---------------------------------------------------------------------------


@dataclass(kw_only=True)
class ControlInputAuditRecord:
    """An immutable record of one processed ControlInput.

    Created by InputOrchestrator.inject() for every control input, regardless
    of whether it was scheduled, contingent, or manually submitted. The record
    captures enough information to reproduce the decision and its effects.

    Attributes:
        record_id: Unique identifier for this audit record.
        scenario_id: Scenario this record belongs to.
        session_id: Session within which this input was processed.
        timestep: Simulation timestep at which the input was applied.
        input_type: Class name of the ControlInput subclass.
        source: Channel through which the input arrived.
        actor_id: Actor who authorised the input.
        actor_role: Role of the authorising actor.
        justification: Human-readable rationale recorded at input time.
        raw_input: Full serialised ControlInput as a dict. Sufficient to
            reconstruct the original input for scenario replay.
        translated_events: List of event_ids generated by to_events().
            Allows correlation between audit records and simulation effects.
        timestamp: Wall-clock time when this record was created.
    """

    record_id: str
    scenario_id: str
    session_id: str
    timestep: datetime
    input_type: str
    source: InputSource
    actor_id: str
    actor_role: str
    justification: str
    raw_input: dict[str, Any]
    translated_events: list[str]
    timestamp: datetime


# ---------------------------------------------------------------------------
# In-memory audit log (Milestone 1)
# ---------------------------------------------------------------------------


class AuditLog:
    """In-memory collection of ControlInputAuditRecords.

    Accumulates every record produced during a session. Provides query
    methods for retrieving records by session or by timestep.

    This implementation is Milestone 1 only. Milestone 2 replaces the
    in-memory list with a PostgreSQL-backed persistent store. The interface
    (append, get_records_for_session, get_records_for_timestep) is stable.
    """

    def __init__(self) -> None:
        """Initialise an empty audit log."""
        self._records: list[ControlInputAuditRecord] = []

    @property
    def records(self) -> list[ControlInputAuditRecord]:
        """All records accumulated so far, in insertion order."""
        return list(self._records)

    def append(self, record: ControlInputAuditRecord) -> None:
        """Append one audit record to the log.

        Args:
            record: The audit record to store.
        """
        self._records.append(record)

    def get_records_for_session(self, session_id: str) -> list[ControlInputAuditRecord]:
        """Return all records for a given session, in insertion order.

        Args:
            session_id: Session identifier to filter by.

        Returns:
            Ordered list of records belonging to the session.
        """
        return [r for r in self._records if r.session_id == session_id]

    def get_records_for_timestep(
        self, timestep: datetime
    ) -> list[ControlInputAuditRecord]:
        """Return all records processed at a given simulation timestep.

        Args:
            timestep: Simulation timestep to filter by.

        Returns:
            Ordered list of records from that timestep.
        """
        return [r for r in self._records if r.timestep == timestep]

    def __len__(self) -> int:
        """Return the number of records accumulated."""
        return len(self._records)
