"""
ScenarioRunner — minimum viable orchestrator for Milestone 1 (ADR-002).

ScenarioRunner is the concrete InputOrchestrator for Milestone 1. It accepts
a fully-specified scenario as Python objects (initial state, scheduled inputs,
modules) and executes it synchronously, returning the complete state history.

The full async InputOrchestrator (serving the web API) is a Milestone 2
deliverable. ScenarioRunner's interface is identical — callers that use the
InputOrchestrator ABC will work unchanged when the web orchestrator replaces
this runner.
"""

from __future__ import annotations

import dataclasses
import uuid
from abc import ABC, abstractmethod
from datetime import datetime, timedelta  # noqa: TCH003 — used at runtime in _advance_timestep
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:

    from app.simulation.engine.models import Event, SimulationModule, SimulationState
    from app.simulation.orchestration.audit import AuditLog
    from app.simulation.orchestration.inputs import (
        ContingentInput,
        ControlInput,
    )


# ---------------------------------------------------------------------------
# InputOrchestrator ABC
# ---------------------------------------------------------------------------


class InputOrchestrator(ABC):
    """Abstract base class for all input orchestrators.

    The orchestrator is the sole entry point for exogenous control inputs.
    All input channels (UI, API, CLI, contingent triggers, scenario scripts)
    converge here. Every input is validated, translated to Events, and recorded
    in the audit log before reaching the propagation engine.

    Concrete implementations:
    - ScenarioRunner: synchronous, in-process (Milestone 1)
    - WebOrchestrator: async, database-backed (Milestone 2)
    """

    @abstractmethod
    def inject(
        self,
        control_input: ControlInput,
        session_id: str,
    ) -> list[Event]:
        """Validate, translate, audit-log, and return Events for one input.

        Args:
            control_input: The exogenous input to process.
            session_id: Session context for the audit record.

        Returns:
            List of Events generated by the input's to_events() method.
        """

    @abstractmethod
    def advance_timestep(
        self,
        current_state: SimulationState,
        modules: list[SimulationModule],
        scheduled_inputs: list[ControlInput],
    ) -> SimulationState:
        """Execute one full simulation tick.

        Collects scheduled inputs (injecting each via inject()), runs all
        modules for each entity, merges exogenous and endogenous events,
        propagates through the relationship graph, and returns State[T+1].

        Args:
            current_state: State[T]. Treated as read-only.
            modules: Simulation modules to run this tick.
            scheduled_inputs: Exogenous inputs to inject this tick.

        Returns:
            State[T+1] with all deltas applied and timestep advanced.
        """

    @abstractmethod
    def check_contingents(self, state: SimulationState) -> list[ControlInput]:
        """Evaluate registered ContingentInputs against current state.

        Returns the ControlInputs whose conditions are met and whose
        cooldown has expired.

        Args:
            state: Current simulation state to evaluate conditions against.

        Returns:
            List of ControlInputs ready to fire.
        """


# ---------------------------------------------------------------------------
# ScenarioRunner
# ---------------------------------------------------------------------------


class ScenarioRunner(InputOrchestrator):
    """Minimum viable orchestrator for Milestone 1.

    Executes a fully-specified scenario synchronously and returns the complete
    state history as a list. Designed for scripted scenarios, the CLI demo,
    and unit tests. Implements the full InputOrchestrator interface so it
    can be replaced by the web orchestrator in Milestone 2 without changing
    any caller code.

    scheduled_inputs is a list of (step_index, ControlInput) tuples. Step 0
    is the initial state; an input at step_index=1 fires before the first
    advance (i.e. at the transition from step 0 to step 1).

    Example::

        runner = ScenarioRunner(
            initial_state=state,
            scheduled_inputs=[(1, tariff_shock)],
            modules=[],
            n_steps=10,
        )
        history = runner.run()
        # history[0] is initial_state
        # history[1] is state after step 1 with tariff_shock applied
        # history[10] is final state
    """

    def __init__(
        self,
        initial_state: SimulationState,
        scheduled_inputs: list[tuple[int, ControlInput]],
        modules: list[SimulationModule],
        n_steps: int,
        audit_log: AuditLog | None = None,
        contingent_inputs: list[ContingentInput] | None = None,
        session_id: str | None = None,
        timestep_delta: timedelta | None = None,
    ) -> None:
        """Initialise the scenario runner.

        Args:
            initial_state: Starting SimulationState (step 0).
            scheduled_inputs: (step_index, ControlInput) pairs. Multiple
                inputs at the same step index fire in list order.
            modules: SimulationModules to run each tick.
            n_steps: Total number of steps to advance. History length
                will be n_steps + 1 (including initial state).
            audit_log: AuditLog to record injected inputs. If None, an
                empty in-memory AuditLog is created.
            contingent_inputs: ContingentInputs to evaluate each step.
                None means no contingent triggers.
            session_id: Session identifier for audit records. If None,
                a UUID is generated.
            timestep_delta: Time advance per step as a fixed timedelta. Pass
                None (the default) to use calendar-year arithmetic, which
                advances by exactly one year on the calendar regardless of
                whether leap years fall in the path. Pass an explicit timedelta
                for sub-annual or non-standard timestep intervals.
        """
        from app.simulation.orchestration.audit import AuditLog as _AuditLog

        self._initial_state = initial_state
        self._scheduled_inputs = scheduled_inputs
        self._modules = modules
        self._n_steps = n_steps
        self._audit_log = audit_log if audit_log is not None else _AuditLog()
        self._contingent_inputs: list[ContingentInput] = (
            contingent_inputs if contingent_inputs is not None else []
        )
        self._session_id = session_id if session_id is not None else str(uuid.uuid4())
        # None means "use calendar-year arithmetic"; see _advance_timestep().
        self._timestep_delta: timedelta | None = timestep_delta
        # contingent_id -> remaining cooldown periods (0 means ready to fire)
        self._cooldown_remaining: dict[str, int] = {}

    @property
    def audit_log(self) -> AuditLog:
        """The audit log accumulating records for this runner's session."""
        return self._audit_log

    @property
    def session_id(self) -> str:
        """Session identifier used in all audit records from this runner."""
        return self._session_id

    def run(self) -> list[SimulationState]:
        """Execute the full scenario and return the complete state history.

        Advances n_steps times from the initial state. At each step, fires
        scheduled inputs, evaluates contingents, runs modules, and propagates.

        Returns:
            List of SimulationStates of length n_steps + 1. Index 0 is the
            initial state. Index i is the state after i steps have been taken.
        """
        history: list[SimulationState] = [self._initial_state]
        current_state = self._initial_state

        for step_index in range(1, self._n_steps + 1):
            step_inputs = [
                inp
                for (idx, inp) in self._scheduled_inputs
                if idx == step_index
            ]
            current_state = self.advance_timestep(
                current_state=current_state,
                modules=self._modules,
                scheduled_inputs=step_inputs,
            )
            history.append(current_state)
            self._decrement_cooldowns()

        return history

    def inject(
        self,
        control_input: ControlInput,
        session_id: str,
    ) -> list[Event]:
        """Translate one ControlInput to Events and record it in the audit log.

        Calls control_input.to_events() with the current simulation timestep,
        then appends a ControlInputAuditRecord capturing the full provenance.

        Args:
            control_input: The exogenous input to process.
            session_id: Session identifier for the audit record.

        Returns:
            Events generated by the input's to_events() method.
        """
        from datetime import datetime as _datetime

        from app.simulation.orchestration.audit import ControlInputAuditRecord

        now = _datetime.utcnow()
        events = control_input.to_events(control_input.effective_date or now)
        record = ControlInputAuditRecord(
            record_id=str(uuid.uuid4()),
            scenario_id=self._initial_state.scenario_config.scenario_id,
            session_id=session_id,
            timestep=control_input.effective_date or now,
            input_type=type(control_input).__name__,
            source=control_input.source,
            actor_id=control_input.actor_id,
            actor_role=control_input.actor_role,
            justification=control_input.justification,
            raw_input=_serialise_input(control_input),
            translated_events=[e.event_id for e in events],
            timestamp=now,
        )
        self._audit_log.append(record)
        return events

    def advance_timestep(
        self,
        current_state: SimulationState,
        modules: list[SimulationModule],
        scheduled_inputs: list[ControlInput],
    ) -> SimulationState:
        """Execute one full simulation tick.

        Order of operations:
        1. Check contingent triggers against current state.
        2. Inject all scheduled inputs (exogenous Events).
        3. Inject all newly-fired contingent inputs.
        4. Run all modules for every entity (endogenous Events).
        5. Merge exogenous and endogenous Events.
        6. Propagate through the relationship graph.
        7. Advance the timestep on the resulting state.

        Args:
            current_state: State[T]. Treated as read-only.
            modules: Simulation modules to run this tick.
            scheduled_inputs: Exogenous inputs to inject this tick.

        Returns:
            State[T+1] with all deltas applied and timestep advanced.
        """
        from app.simulation.engine.propagation import propagate

        all_events: list[Event] = []

        # Exogenous: inject scheduled inputs
        for control_input in scheduled_inputs:
            all_events.extend(self.inject(control_input, self._session_id))

        # Exogenous: inject contingent inputs that just triggered
        for fired_input in self.check_contingents(current_state):
            all_events.extend(self.inject(fired_input, self._session_id))

        # Endogenous: run modules for each entity
        for entity in current_state.entities.values():
            for module in modules:
                endogenous_events = module.compute(
                    entity, current_state, current_state.timestep
                )
                all_events.extend(endogenous_events)

        # Propagate all events and advance the timestep
        next_state = propagate(current_state, all_events)
        return dataclasses.replace(
            next_state,
            timestep=_advance_timestep(current_state.timestep, self._timestep_delta),
        )

    def check_contingents(self, state: SimulationState) -> list[ControlInput]:
        """Evaluate all registered ContingentInputs against current state.

        A contingent fires when its condition is met AND its cooldown has
        expired (cooldown_remaining == 0). When a contingent fires, its
        cooldown is set to cooldown_periods. The fired ControlInput has its
        source overridden to CONTINGENT_TRIGGER.

        Args:
            state: Current simulation state to evaluate conditions against.

        Returns:
            List of ControlInputs ready to fire. May be empty.
        """
        from app.simulation.orchestration.inputs import InputSource

        fired: list[ControlInput] = []
        for contingent in self._contingent_inputs:
            remaining = self._cooldown_remaining.get(contingent.contingent_id, 0)
            if remaining > 0:
                continue
            if contingent.condition.is_met(state):
                triggered_input = dataclasses.replace(
                    contingent.input,
                    source=InputSource.CONTINGENT_TRIGGER,
                )
                fired.append(triggered_input)
                self._cooldown_remaining[contingent.contingent_id] = (
                    contingent.cooldown_periods
                )
        return fired

    def _decrement_cooldowns(self) -> None:
        """Decrement all active cooldown counters by one period.

        Called at the end of each step in run(). A contingent whose counter
        reaches zero becomes eligible to fire again on the next step.
        """
        for key in list(self._cooldown_remaining.keys()):
            if self._cooldown_remaining[key] > 0:
                self._cooldown_remaining[key] -= 1


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _advance_timestep(current: datetime, delta: timedelta | None) -> datetime:
    """Compute the next timestep, handling leap years correctly.

    When delta is None (the default for annual simulations), advances by
    exactly one calendar year using date arithmetic. This correctly handles
    leap years: 2027-01-01 + 1 year = 2028-01-01, and 2028-01-01 + 1 year
    = 2029-01-01, with no day-count drift.

    The timedelta(days=365) approach fails at leap-year boundaries: adding
    365 days to 2028-01-01 (a leap year has 366 days) lands on 2028-12-31,
    causing two consecutive steps to display the same year.

    When delta is an explicit timedelta, it is used as-is. This supports
    sub-annual timesteps (monthly, weekly) where fixed day counts are correct.

    Args:
        current: The current timestep.
        delta: Fixed timedelta to add, or None to advance by one calendar year.

    Returns:
        Next timestep.
    """
    if delta is not None:
        return current + delta
    try:
        return current.replace(year=current.year + 1)
    except ValueError:
        # Feb 29 in a leap year advancing to a non-leap year → Feb 28
        return current.replace(year=current.year + 1, day=28)


def _serialise_input(control_input: ControlInput) -> dict[str, Any]:
    """Produce a dict representation of a ControlInput for audit storage.

    Uses dataclasses.asdict() with special handling for non-serialisable
    fields (Decimal -> str, Enum -> .value, datetime -> .isoformat()).
    Nested dataclasses are recursed automatically by dataclasses.asdict().

    Args:
        control_input: The ControlInput to serialise.

    Returns:
        Dict suitable for JSON serialisation and audit log storage.
    """
    from datetime import datetime as _datetime
    from decimal import Decimal as _Decimal
    from enum import Enum as _Enum

    raw = dataclasses.asdict(control_input)

    def _coerce(obj: Any) -> Any:  # noqa: ANN401 — recursive coercion over unknown nested types
        if isinstance(obj, _Decimal):
            return str(obj)
        if isinstance(obj, _Enum):
            return obj.value
        if isinstance(obj, _datetime):
            return obj.isoformat()
        if isinstance(obj, dict):
            return {k: _coerce(v) for k, v in obj.items()}
        if isinstance(obj, list):
            return [_coerce(item) for item in obj]
        return obj

    return {k: _coerce(v) for k, v in raw.items()}
